### ISSUE TITLE
Make the project license clearly GNU General Public License

### ISSUE THREAD

**Issue by puybaret** [alessandropellegrini/sh3d-headless-renderer#1]
Thanks for this project :)
Note that Sweet Home 3D is released under the GNU General Public License which obliges any project derived from it to be released under the same license.
So please, make it clear that your project is avalaible under GNU General Public License, fix the headers of the source files which uses Sweet Home 3D packages (at least CameraRenderer.java) and add headers with a license in the source files without any header yet. The later files can be released under another free license compatible with GNU GPL but if you make them available under GNU GPL too, they should have the GNU GPL header.
Thanks!

**Comment by alessandropellegrini** [comment]
Hi Emmanuel,
thanks for pointing it out. With the last commit, the project is now REUSE compliant, so all licensing issues have been cleared.
